import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#FAF9F9",
        "surface-dim": "#DADADA",
        "surface-bright": "#FAF9F9",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F4F3F3",
        "surface-container": "#EEEEED",
        "surface-container-high": "#E9E8E8",
        "surface-container-highest": "#E3E2E2",
        "on-surface": "#1A1C1C",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2F3131",
        "inverse-on-surface": "#F1F0F0",
        outline: "#747878",
        "outline-variant": "#C4C7C7",
        "surface-tint": "#5F5E5E",
        primary: "#000000",
        "on-primary": "#FFFFFF",
        "primary-container": "#1C1B1B",
        "on-primary-container": "#858383",
        "inverse-primary": "#C8C6C5",
        secondary: "#5D5F5C",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E2E3DF",
        "on-secondary-container": "#636562",
        tertiary: "#000000",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#410003",
        "on-tertiary-container": "#FA3434",
        error: "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
        "primary-fixed": "#E5E2E1",
        "primary-fixed-dim": "#C8C6C5",
        "on-primary-fixed": "#1C1B1B",
        "on-primary-fixed-variant": "#474746",
        "secondary-fixed": "#E2E3DF",
        "secondary-fixed-dim": "#C6C7C3",
        "on-secondary-fixed": "#1A1C1A",
        "on-secondary-fixed-variant": "#454745",
        "tertiary-fixed": "#FFDAD6",
        "tertiary-fixed-dim": "#FFB4AC",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#93000E",
        background: "#FAF9F9",
        "on-background": "#1A1C1C",
        "surface-variant": "#E3E2E2",
        "accent-red": "#E22026",
        "accent-yellow": "#FFD500",
        "accent-blue": "#0055AD",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "unit-1": "0.5rem",
        "unit-2": "1rem",
        "unit-3": "1.5rem",
        "unit-4": "2rem",
        "unit-8": "4rem",
        "unit-12": "6rem",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        syne: ["var(--font-syne)", "sans-serif"],
        hanken: ["var(--font-hanken)", "sans-serif"],
        jetbrains: ["var(--font-jetbrains)", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
